/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package exemplo26_bolinhas;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;

/**
 *
 * @author Maria11
 */
public class JPanelBolinhas extends javax.swing.JPanel {
    private float ballRadius = 20;
    private final static int QUANTIDADE=100;
    private final static int LARGURA=1000;
    private final static int ALTURA=700;
    //Classe_Bola[] b1 = new Classe_Bola[QUANTIDADE];
    Classe_BolinhaComCor[] b1 = new Classe_BolinhaComCor[QUANTIDADE];
    
    /**
     * Creates new form JPanelBolinhas
     */
    public JPanelBolinhas() {
        initComponents();
        this.setPreferredSize(new Dimension(LARGURA, ALTURA));
        
        Thread gameThread = new Thread(){
            public void run(){
                int j;
                for(j=0; j < QUANTIDADE; j++)
                    b1[j]= new Classe_BolinhaComCor();
                
                while(true){
                    for(j=0; j < QUANTIDADE; j++)
                    {
                        b1[j].setBallX(b1[j].getBallX()+ b1[j].getBallSpeedX());
                        b1[j].setBallY(b1[j].getBallY()+ b1[j].getBallSpeedY());
                        if (b1[j].getBallX()< 0)
                            b1[j].setBallSpeedX(-b1[j].getBallSpeedX());
                        if(b1[j].getBallX() > LARGURA-2*b1[j].Radius)
                             b1[j].setBallSpeedX(-b1[j].getBallSpeedX());
                        
                        if (b1[j].getBallY()< 0)
                            b1[j].setBallSpeedY(-b1[j].getBallSpeedY());
                        if(b1[j].getBallY() > ALTURA-2*b1[j].Radius)
                             b1[j].setBallSpeedY(-b1[j].getBallSpeedY());
                    }
                    repaint();
                    try
                    {
                        Thread.sleep(10);
                    }
                    catch(Exception ex)
                    {
                    
                    }
                }
            }
        };
        gameThread.start();
    }
        
        @Override
        public void paintComponent(Graphics g)
        {
            super.paintComponent(g);//vai buscar componnets da classe mãe JPanel
            g.setColor(Color.BLUE);
            g.fillRect(0,0, LARGURA, ALTURA);
            int j;
            for (j=0; j< QUANTIDADE; j++)
            {
                g.setColor(new Color(b1[j].getR(),b1[j].getG(),b1[j].getB()));
                g.fillOval((int)(b1[j].getBallX()), (int)(b1[j].getBallY()), (int)(2 * b1[j].Radius), (int)(2 * b1[j].Radius));
            }
        }   
   
        


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
