/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package exemplo14_conversor;

/**
 *
 * @author Maria11
 */
public class Classe_Java extends javax.swing.JFrame {

    /**
     * Creates new form Classe_Java
     */
    public Classe_Java() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldEuro = new javax.swing.JTextField();
        jTextFieldDolar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldLibra = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 0));
        jLabel1.setText("Conversor de Moedas");

        jTextFieldEuro.setForeground(new java.awt.Color(0, 51, 51));
        jTextFieldEuro.setText("0");
        jTextFieldEuro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldEuroKeyReleased(evt);
            }
        });

        jTextFieldDolar.setForeground(new java.awt.Color(0, 51, 51));
        jTextFieldDolar.setText("0");
        jTextFieldDolar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldDolarKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("€");

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("$");

        jTextFieldLibra.setForeground(new java.awt.Color(0, 51, 51));
        jTextFieldLibra.setText("0");
        jTextFieldLibra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldLibraKeyReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("£");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldDolar, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldEuro, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2))
                            .addComponent(jTextFieldLibra, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldEuro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDolar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldLibra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldEuroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldEuroKeyReleased
       String s1= jTextFieldEuro.getText();//Caixa de euros -> s1 que é string
       float f1 = Float.parseFloat(s1);//converte s1 em float-f1
       float dolares = f1 * 1.2f;//multiplica pela cotação euros-dolares 1.2
       String sDolares = String.valueOf(dolares);//converte dolares em string ->dolares
       jTextFieldDolar.setText(sDolares);//mostra na caixa dos dolares
       
       float f3 = Float.parseFloat(s1);//converte s1 em float-f1
       float libras = f1 / 1.15f;//multiplica pela cotação euros-dolares 1.2
       String sLibras = String.valueOf(libras);//converte dolares em string ->dolares
       jTextFieldLibra.setText(sLibras);//mostra na caixa dos dolares
       
       
       
    }//GEN-LAST:event_jTextFieldEuroKeyReleased

    private void jTextFieldDolarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDolarKeyReleased
       String s2= jTextFieldDolar.getText();
       float f2 = Float.parseFloat(s2);//converte s1 em float-f1
       float euros = f2 / 1.2f;//multiplica pela cotação euros-dolares 1.2
       String sEuros = String.valueOf(euros);//converte dolares em string ->dolares
       jTextFieldEuro.setText(sEuros);//mostra na caixa dos dolares
       
       float f4 = Float.parseFloat(sEuros);//converte s1 em float-f1
       float libras = euros / 1.15f;//multiplica pela cotação euros-dolares 1.2
       String sLibras = String.valueOf(libras);//converte dolares em string ->dolares
       jTextFieldLibra.setText(sLibras);//mostra na caixa dos dolares
       
    }//GEN-LAST:event_jTextFieldDolarKeyReleased

    private void jTextFieldLibraKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldLibraKeyReleased
        String s3 = jTextFieldLibra.getText();
        float f5  = Float.parseFloat(s3);
        float euros = f5 * 1.15f;
         String sEuros = String.valueOf(euros);
        jTextFieldEuro.setText(sEuros);
        
        float f6 = Float.parseFloat(sEuros);
        float dolares = euros * 1.2f;
        String sDolares = String.valueOf(dolares);
        jTextFieldDolar.setText(sDolares);
        
    }//GEN-LAST:event_jTextFieldLibraKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Classe_Java.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Classe_Java.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Classe_Java.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Classe_Java.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Classe_Java().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextFieldDolar;
    private javax.swing.JTextField jTextFieldEuro;
    private javax.swing.JTextField jTextFieldLibra;
    // End of variables declaration//GEN-END:variables
}
